name: bedwars
version: '${project.version}'
main: com.test.bedwars.BedwarsPlugin
commands:
  setup:
    description: Setup a map
  start:
    description: Start the game
  reset:
    description: Reset the game